name: Release Archive

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archives
        run: |
          REPO_NAME=$(basename "${{ github.repository }}")
          ARCHIVE_DIR="release_tmp/$REPO_NAME"

          # Создаём структуру: release_tmp/имя_проекта
          mkdir -p "$ARCHIVE_DIR"

          # Копируем всё, кроме временной папки, .git и .github
          rsync -a \
            --exclude='release_tmp' \
            --exclude='.git' \
            --exclude='.github' \
            ./ "$ARCHIVE_DIR/"

          # Собираем архивы (внутри будет папка с именем проекта)
          cd release_tmp
          zip -r "../$REPO_NAME.zip" "$REPO_NAME"

      - name: Upload archives as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.event.repository.name }}.zip

      - name: Attach archives to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}.zip
